name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run sfml install script  
      run: |
        sudo apt-get install libx11-dev libxrandr-dev libxcursor-dev libxi-dev && sh -c rsc/init_sfml.sh

    - name: Run make
      run: make

    - name: clean
      run: make fclean
